<?php
/**
 * @file
 * idei_capability_nodes_and_taxonomy.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function idei_capability_nodes_and_taxonomy_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Consultancy Assignment',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1be09964-6614-4a57-b74e-53990d79dc39',
    'vocabulary_machine_name' => 'capability',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Impact',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2a2d2e49-4c82-4a17-b07f-df433a5c55f4',
    'vocabulary_machine_name' => 'capability',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Implementing multidisciplinary capacity building',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5cc54374-a70f-4d75-aef5-a96fada8c172',
    'vocabulary_machine_name' => 'capability',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'IDEI\'s Strategy',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5faffd1f-7a8c-467a-a1ff-caae4fd2d2cc',
    'vocabulary_machine_name' => 'capability',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Profile of the organisation.',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '67298de8-523c-413f-9549-a38c24a6b978',
    'vocabulary_machine_name' => 'capability',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Image Section: 84% OF INDIA',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '71e97a4c-8b97-4e7c-977d-ac921927b103',
    'vocabulary_machine_name' => 'capability',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Awards',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '7a27887d-210d-4566-aba0-18ae272b5b07',
    'vocabulary_machine_name' => 'capability',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Image Section: 1,000 Dealers',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '947407a7-c83f-4c85-b99f-0a1daf7b0c28',
    'vocabulary_machine_name' => 'capability',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Image Section: USD 7.3 Billion',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a4e9cdae-8297-4964-99b9-dd6a34ba561e',
    'vocabulary_machine_name' => 'capability',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Image Section: 200 STAFF',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a74a2ccf-90e9-4ca8-aa1c-6a240963c2dc',
    'vocabulary_machine_name' => 'capability',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Implementing multidisciplinary resource',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'adec7a1b-f91b-413e-b6ee-8f23eda8a1e6',
    'vocabulary_machine_name' => 'capability',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Working with the government',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c0d05d8c-21fe-463b-83c1-39c3163b255e',
    'vocabulary_machine_name' => 'capability',
    'path' => array(
      'pathauto' => 0,
    ),
  );
  $terms[] = array(
    'name' => 'Profile of the organisation accordions',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => 'c76de39e-f3f3-41cc-b4e4-c297fde236a8',
    'vocabulary_machine_name' => 'capability',
    'path' => array(
      'pathauto' => 0,
    ),
  );
  $terms[] = array(
    'name' => 'Management of inter disciplinary projects',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd5efec59-ba09-40d6-a7da-ce162564ab41',
    'vocabulary_machine_name' => 'capability',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Working with NGOs and CBOs',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e5c96304-b16d-497d-99f1-9c86d6d24257',
    'vocabulary_machine_name' => 'capability',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Techinical Expertise',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e8a717ba-ff1c-4e12-8807-0858892f8c94',
    'vocabulary_machine_name' => 'capability',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'IDEI CAPABILITY STATEMENT',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f625b3ba-d3d5-4e0b-927f-f8ccae85a960',
    'vocabulary_machine_name' => 'capability',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'setting up project monitoring',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'ffc4b09f-f17b-47b8-aca6-ad9c69346271',
    'vocabulary_machine_name' => 'capability',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  return $terms;
}
