<?php 

/**
 * Implements hook_init().
 */
function idei_custom_init() {
  drupal_add_js(drupal_get_path('module', 'idei_custom') . '/js/jquery.anchor.js');
}
/**
* Implements hook_block_info().
*/
function idei_custom_block_info() {
  $blocks = array();

  $blocks['home_custom_menu'] = array(
    'info' => t('Home custom menu'),
  );
  $blocks['programs_custom_menu'] = array(
    'info' => t('Programs custom menu'),
  );
  $blocks['Products_gallery_tab_block'] = array(
    'info' => t('Product Tab Block'),
  );

  return $blocks;
}

/**
* Implements hook_block_view().
*/
function idei_custom_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'home_custom_menu':
      $block['subject'] = '';
      $block['content'] = idei_main_custom_navigation();
      break;
    case 'programs_custom_menu':
      $block['subject'] = '';
      $block['content'] = idei_program_navigation();
      break;
    case 'Products_gallery_tab_block':
      $block['subject'] = '';
      $block['content'] = program_tab_block();
  }

  return $block;
}

function program_tab_block() {
  drupal_add_js( drupal_get_path('module', 'idei_custom') . '/js/easyResponsiveTabs.js');
  drupal_add_js( drupal_get_path('module', 'idei_custom') . '/js/responsiveTabs.js');
  drupal_add_css( drupal_get_path('module', 'idei_custom') . '/css/easy-responsive-tabs.css');
  return theme('program_tabs');
}


function idei_program_navigation(){
  return theme('idei_program');
}

/*
 * Implementation of hook_theme().
 */
function idei_custom_theme(){
  $templates = array(
    'idei_custom_block' => array(     
      'template' => 'templates/idei-custom-menu-new',
    ),
    'idei_program' => array(     
     'template' => 'templates/idei-programs-menu',
    ),
    'program_tabs' => array(
     'template' =>'templates/program-tab-block',
    ),
  );
  return $templates;
}

function idei_main_custom_navigation() {
  return theme('idei_custom_block'); 
}

function idei_custom_form_alter(&$form, &$form_state, $form_id) {

  if($form_id == 'webform_client_form_67') {
    $argument = $_REQUEST['nid'];
    $node = node_load($argument);
    $pdf_name = $node->field_publication_pdf['und'][0]['uri'];
    $pdf_name = explode("//",$pdf_name);
    $pdf = $pdf_name[1];
    global $base_url;
    $pdf_file_url = $base_url.'/sites/default/files/'.$pdf;
    $form['submitted']['url_path']['#default_value']= $pdf_file_url;
 }
}




