<?php 

/**
 * Implements hook_init().
 */
function idei_custom_init() {

  drupal_add_js(drupal_get_path('module', 'idei_custom') . '/js/jquery.anchor.js');

}
/**
* Implements hook_block_info().
*/
function idei_custom_block_info() {
  $blocks = array();

  $blocks['home_custom_menu'] = array(
    'info' => t('Home custom menu'),
  );

  return $blocks;
}

/**
* Implements hook_block_view().
*/
function idei_custom_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'home_custom_menu':
      $block['subject'] = '';
      $block['content'] = idei_main_custom_navigation();
      break;
  }

  return $block;
}
/*
** Display custom main menubar on homepage top.
*/
/*function main_custom_navigation() {


  $result = db_select('menu_links', 'n') 
    ->fields('n',array('link_title','link_path')) 
    ->condition('menu_name', 'main-menu','=') 
    ->condition('plid', 0,'=') 
    ->orderBy('weight', 'ASC') 
    ->execute() 
    ->fetchAll(); 
  $output .='<ul class="custom-navigation">';
    foreach ($result as $key => $value) {
      if($value->link_path =='<front>'){ 
        $path='';
      }
      else {
        $path=$value->link_path;
      }
  $output .= '<li><span id="top-links-'.$key.'" class="paralax">'.$value->link_title.'</span></li>';
    }
  $output .='</ul>';

return $output;

}*/

/*
 * Implementation of hook_theme().
 */
function idei_custom_theme(){

  $templates = array(
    'idei_custom_block' => array(
      
      'template' => 'templates/idei-custom-menu-new',
    ),
  );
  return $templates;
}


function idei_main_custom_navigation() {
  
  return theme('idei_custom_block'); 

}

/**
 * Implements hook_menu_block_blocks().
 */
function idei_custom_menu_block_blocks() {
  // The array key is the block delta used by menu block.
  return array(
    'idei_custom-1' => array(
      'parent'      => main-menu:347,
      'title_link'  => 0,
      'admin_title' => 'Approach Menu Block',
      'level'       => 1,
      'follow'      => '0',
      'depth'       => 0,
      'expanded'    => 0,
      'sort'        => 0,
    ),
    'idei_custom-2' => array(
      'parent'      => main-menu:348,
      'title_link'  => 0,
      'admin_title' => 'Menu Block  For Programs',
      'level'       => 1,
      'follow'      => '0',
      'depth'       => 0,
      'expanded'    => 0,
      'sort'        => 0,
    ),
    'idei_custom-3' => array(
      'parent'      => main-menu:349,
      'title_link'  => 0,
      'admin_title' => 'Menu block for Water',
      'level'       => 1,
      'follow'      => '0',
      'depth'       => 0,
      'expanded'    => 0,
      'sort'        => 0,
    ),
  );
}

?>