<?php
/**
 * @file
 * paralax_menubar.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function paralax_menubar_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: main-menu_about-us:node/21.
  $menu_links['main-menu_about-us:node/21'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/21',
    'router_path' => 'node/%',
    'link_title' => 'ABOUT US',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_about-us:node/21',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: main-menu_archives:<front>.
  $menu_links['main-menu_archives:<front>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'ARCHIVES',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_archives:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
  );
  // Exported menu link: main-menu_awards:<front>.
  $menu_links['main-menu_awards:<front>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'AWARDS',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_awards:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
  );
  // Exported menu link: main-menu_engage:<front>.
  $menu_links['main-menu_engage:<front>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'ENGAGE',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_engage:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -41,
    'customized' => 1,
  );
  // Exported menu link: main-menu_partners:<front>.
  $menu_links['main-menu_partners:<front>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'PARTNERS',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_partners:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
  );
  // Exported menu link: main-menu_programs:<front>.
  $menu_links['main-menu_programs:<front>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'PROGRAMS',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_programs:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
  );
  // Exported menu link: main-menu_water:<front>.
  $menu_links['main-menu_water:<front>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'WATER',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_water:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
  );
  // Exported menu link: menu-approach_idei-approach:node/57.
  $menu_links['menu-approach_idei-approach:node/57'] = array(
    'menu_name' => 'menu-approach',
    'link_path' => 'node/57',
    'router_path' => 'node/%',
    'link_title' => 'IDEI Approach',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-approach_idei-approach:node/57',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-approach_the-context:node/58.
  $menu_links['menu-approach_the-context:node/58'] = array(
    'menu_name' => 'menu-approach',
    'link_path' => 'node/58',
    'router_path' => 'node/%',
    'link_title' => 'The Context',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-approach_the-context:node/58',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-programs_climate-smart-agriculture-:node/37.
  $menu_links['menu-programs_climate-smart-agriculture-:node/37'] = array(
    'menu_name' => 'menu-programs',
    'link_path' => 'node/37',
    'router_path' => 'node/%',
    'link_title' => 'CLIMATE SMART AGRICULTURE ',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-programs_climate-smart-agriculture-:node/37',
      'fragment' => 'program-3',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: menu-programs_income-enhancement-:node/37.
  $menu_links['menu-programs_income-enhancement-:node/37'] = array(
    'menu_name' => 'menu-programs',
    'link_path' => 'node/37',
    'router_path' => 'node/%',
    'link_title' => 'INCOME ENHANCEMENT ',
    'options' => array(
      'fragment' => 'program-2',
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-programs_income-enhancement-:node/37',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-programs_ipmas:node/37.
  $menu_links['menu-programs_ipmas:node/37'] = array(
    'menu_name' => 'menu-programs',
    'link_path' => 'node/37',
    'router_path' => 'node/%',
    'link_title' => 'IPMAS',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-programs_ipmas:node/37',
      'fragment' => 'program-5',
    ),
    'module' => 'menu',
    'hidden' => 1,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
  );
  // Exported menu link: menu-programs_market-developmnet:node/37.
  $menu_links['menu-programs_market-developmnet:node/37'] = array(
    'menu_name' => 'menu-programs',
    'link_path' => 'node/37',
    'router_path' => 'node/%',
    'link_title' => 'MARKET DEVELOPMNET',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-programs_market-developmnet:node/37',
      'fragment' => 'program-4',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
  );
  // Exported menu link: menu-programs_sustainable-agriculture:node/37.
  $menu_links['menu-programs_sustainable-agriculture:node/37'] = array(
    'menu_name' => 'menu-programs',
    'link_path' => 'node/37',
    'router_path' => 'node/%',
    'link_title' => 'SUSTAINABLE AGRICULTURE',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-programs_sustainable-agriculture:node/37',
      'fragment' => 'program-1',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-water_india-facts:<front>.
  $menu_links['menu-water_india-facts:<front>'] = array(
    'menu_name' => 'menu-water',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'INDIA FACTS',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-water_india-facts:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: menu-water_introduction:<front>.
  $menu_links['menu-water_introduction:<front>'] = array(
    'menu_name' => 'menu-water',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'INTRODUCTION',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-water_introduction:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-water_red-flags:<front>.
  $menu_links['menu-water_red-flags:<front>'] = array(
    'menu_name' => 'menu-water',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'RED FLAGS',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-water_red-flags:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-water_world-facts:<front>.
  $menu_links['menu-water_world-facts:<front>'] = array(
    'menu_name' => 'menu-water',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'WORLD FACTS',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-water_world-facts:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('ABOUT US');
  t('ARCHIVES');
  t('AWARDS');
  t('CLIMATE SMART AGRICULTURE ');
  t('ENGAGE');
  t('IDEI Approach');
  t('INCOME ENHANCEMENT ');
  t('INDIA FACTS');
  t('INTRODUCTION');
  t('IPMAS');
  t('MARKET DEVELOPMNET');
  t('PARTNERS');
  t('PROGRAMS');
  t('RED FLAGS');
  t('SUSTAINABLE AGRICULTURE');
  t('The Context');
  t('WATER');
  t('WORLD FACTS');

  return $menu_links;
}
